name: plant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  connectivity_plus: ^6.1.4
  dio: ^5.9.0
  dio_http2_adapter: ^2.6.0
  dio_smart_retry: ^7.0.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_screenutil: ^5.9.3
  go_router: ^16.1.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/home/
    - assets/icons/paywall/
    - assets/images/onboarding/
    - assets/images/home/
    - assets/images/paywall/
